### ISSUE TITLE
Track progress bar does not reset to 0 when skipping a track or after a track transition

### ISSUE THREAD

**Issue by brandsjek** [polyfloyd/trollibox#12]
When skipping a track, the track progress bar does not reset to 00:00. Instead, it continues where it was when playing the previous track. The duration of the track does update properly. Pausing the track does update the current position into its proper state.

**Comment by brandsjek** [comment]
Might be a PEBCAK, although I remember something like this happening at the space. Will reopen once I confirm.

**Comment by brandsjek** [comment]
This does not appear to be a PEBCAK from my end.

A event should be sent to explicitly indicate that the track progress is 0 after skipping a track.

**Comment by polyfloyd** [comment]
This has been fixed in the rewrite to Vue.js
