### ISSUE TITLE
labels empty

### ISSUE THREAD

**Issue by xkonni** [polyfloyd/trollibox#5]
hey polyfloyd,

running into a rather serious issue and hope you have an idea how to fix it.
unfortunately the information in the playlist always changes to "None" after being correct for a moment.

<img width="1471" alt="screen shot 2017-12-19 at 23 44 17" src="https://user-images.githubusercontent.com/218331/34182461-a6862528-e516-11e7-8e5e-30e36d59a1de.png">

thanks for your time!

**Comment by polyfloyd** [comment]
Weird. Could you tell me which Git hash, player backend (MPD or SlimServer) you have?

**Comment by xkonni** [comment]
sure, it's the latest git version 91b094f and using mpd 0.20.13. 

thank you!

**Comment by xkonni** [comment]
awesome. thanks!
